### ISSUE TITLE
Measurements 

### ISSUE THREAD

**Issue by Jakkipaige** [bricas45/GlobalStrength#6]
I can’t find anywhere to put my measurements just my body weight

**Comment by bricas45** [comment]
Thank you for putting this in!  I partially implemented some of the backend for this already.

Currently just body weight and body fat % are there for tracking.  

You can enter anything in the notes, however, I will add the ability to track standard measurements as well.

I will probably add this in 2 steps/release.  First, adding the ability to enter and second with the ability to graph.  Should have at least the first piece out this week.

**Comment by bricas45** [comment]
version 1.0.159 enables entering of measurements (wrist, arm, shoulder, chest, waist, thigh, knee, and calf circumferences)

future build will handle displaying these back

**Comment by bricas45** [comment]
These can now be entered and reviewed in the data at the bottom of the body metrics page.

Will add some graphing support in future update
